[build]
target = "wasm32-unknown-unknown"
#target-dir = "../output/"

[target."wasm32-unknown-unknown"]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory",
    "-C", "link-args=--shared-memory --features=atomics,bulk-memory --no-check-features"
]

