[unstable]
build-std = ["core", "std", "alloc", "compiler_builtins", "proc_macro", "panic_abort"]
# ["core", "std", "alloc", "compiler_builtins", "proc_macro", "panic_abort"]

[build]
target = "wasm32-unknown-unknown"
#target-dir = "../output/"

[target."wasm32-unknown-unknown"]
# `rust-lld -flavor "wasm" --help`
#linker = "../../llvm-project/build/bin/wasm-ld"
rustflags = [
    # `rustc --print target-features --target wasm32-unknown-unknown`
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "link-args=--shared-memory --features=atomics,bulk-memory,mutable-globals"
]
